dist: xenial

language: python
python:
  - "3.6"
install:
  - pip install -r src/requirements.txt
script:
  - python src/manage.py test

jobs:
  include:
    - stage: build docker arm image
      script:
        # authenticate with docker
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # generate Dockerfile for armv7
      - ./create-dockerfile-arm.sh
      # build armv7 image
      - docker build -f Dockerfile-armv7 -t lardbit/nefarious:armv7 .
      - docker images
      # push to docker hub
      - docker push $DOCKER_USERNAME/nefarious:armv7
