dist: xenial

language: python
python:
  - "3.6"
install:
  - pip install -r src/requirements.txt
script:
  - python src/manage.py test

jobs:
  include:
    - stage: build docker arm image
      script:
      - # build base image
      - docker build -t lardbit/nefarious .
      # build armv7 image copying the app from the previously built base image
      - docker build -f Dockerfile-armv7 -t lardbit/nefarious:armv7 .
      # authenticate with docker
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # push to docker hub
      - docker push $DOCKER_USERNAME/nefarious:armv7
