version: '2.4'

services:

  # nefarious main application
  nefarious:
    extends:
      service: nefarious-app-base
      file: docker-compose.base.yml
    depends_on:
      - redis
      - jackett
      - celery

  # nefarious background task queue
  celery:
    extends:
      service: celery-base
      file: docker-compose.base.yml
    depends_on:
      - redis

  # database for task queue
  redis:
    image: redis
    restart: always
    mem_limit: 200m
    # NOTE: use "ports" when developing so local dev server can access redis
    #ports:
    #  - "6379:6379"
    expose:
      - 6379

  # torrent indexer service
  jackett:
    extends:
      service: jackett-base
      file: docker-compose.base.yml
    ports:
      - "9117:9117"

  # torrent server
  transmission:
    image: linuxserver/transmission
    volumes:
      - ${HOST_DOWNLOAD_PATH:-/tmp}:/downloads
      - ./transmission-settings.json:/config/settings.json:ro
    ports:
      - "9091:9091"
    environment:
      - PUID=${HOST_DOWNLOAD_UID:-1000}
      - PGID=${HOST_DOWNLOAD_GID:-1000}

  # auto update service
  # https://github.com/v2tec/watchtower
  watchtower:
    image: v2tec/watchtower
    restart: always
    command: --label-enable --cleanup
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600
    logging:
      options:
        max-size: 10m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nefarious-db:
  jackett-config:
