name: nefarious
on:
  push:
    branches:
      # TODO
      - github-actions
jobs:
  build-arm:
    name: run unit tests and build images
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.8
        with:
          arch: armv7
          distro: ubuntu18.04
          env: | # YAML, but pipe character is necessary
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            set -e
            # authenticate with docker
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            # create docker network to link containers
            docker network create tests
            # run redis
            docker run --network tests --name redis --rm -d redis
            # store commit in image for version identification
            echo "$TRAVIS_COMMIT" > src/.commit
            # derive the docker image tag name from the git branch name
            if [[ $TRAVIS_BRANCH == 'master' ]]; then tag='latest'; else tag="$TRAVIS_BRANCH"; fi
            # build image
            docker build -t lardbit/nefarious:$tag .
            # run unit tests
            docker run --network tests -e REDIS_HOST=redis --entrypoint /env/bin/python lardbit/nefarious:$tag manage.py test
  push:
    runs-on: ubuntu-18.04
    needs: build-arm
    steps:
      - name: push
        run: |
          # authenticate with docker
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          # push image to docker hub
          docker push lardbit/nefarious:$tag-TEST


